export const UPDATEEDU = "UPDATEEDU";
export const UPDATEWORK = "UPDATEWORK";
export const UPDATEPROFILE = "UPDATEPROFILE";
export const UPDATEPROJ = "UPDATEPROJ";

export const UPDATERESUME = "UPDATERESUME";
export const UPDATELANGUAGE = "UPDATELANGUAGE";
export const UPDATEOTHER = "UPDATEOTHER";
export const REMOVELANGUAGE = "REMOVELANGUAGE";
export const REMOVEOTHER = "REMOVEOTHER";

export const SETTIP = "SETTIP";